In [1]:
# NUMPY contain: 1. high-level number objects: int,float 
       # 2. containers: Lists,dictonaries

In [ ]:
'''NUMPY provides: 
         1. extension package to python for multi dimension arrays
         2. closure to hardware(Effeciency)
         3. designed for scientific computation(Convinence)
         4. also known as array oriented computing '''

In [1]:
# create a simple array using numpy
import numpy as np

array = np.array([1,2,3,4,5])
print(array)

print(np.arange(10))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
# %timeit : return time taken took per iteration:
L = range(100)
%timeit [i**2 for i in L]

56.3 µs ± 545 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
# Nano is smaller than micro:
# here it took nano sec but in above one:
   #it took micro so this is faster 

a = np.arange(100)
%timeit a**2

614 ns ± 9.75 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
# find dimension of array:
print(a.ndim)

# find size of array:
print(a.shape)
# or
len(a)

1
(5,)


5

In [20]:
# 2D-array:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Dimension of Array:
print(b.ndim)

# find size of array:
print(b.shape)    # returns (row,column)

# length of array:
print(len(b))   # returns size of first dimension array

2
(2, 3)
2


In [33]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #  [[]]-3d array
c                                         #  [] - 2d array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
print(c.ndim)

print(c.shape) # Returns (length,breadth,height)

print(len(c)) # returns size of first dimension array

3
(2, 2, 2)
2


In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = np.arange(1,10,2) # same as slicing [start,stop,stepsize]
b

array([1, 3, 5, 7, 9])

In [56]:
c = np.linspace(0,1,6) # start , end, number of points
c         #6: it divides and give 6 equal points

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [77]:
a = np.ones((3,3),dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
b = np.zeros((3,3))
b 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
c = np.eye(3) # 2-D array with diagonal elements as 1
c             # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
c = np.eye(3,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [67]:
# create array using diag function:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [68]:
# Extract diagonal:
np.diag(a)

array([1, 2, 3, 4])

In [73]:
# create array of random values:
a = np.random.randint(10,size = (3,3)) # 10:last num to be in matrix
a                                      # size: which matrix

array([[4, 1, 9],
       [3, 9, 1],
       [3, 6, 8]])

In [75]:
b = np.random.rand(3,3)
b

array([[0.48558888, 0.25100064, 0.74911318],
       [0.41533163, 0.7148081 , 0.58329814],
       [0.04280096, 0.90163377, 0.17668129]])

In [76]:
c = np.random.randn(3,3)
c

array([[-0.14988049,  1.32298552, -2.12975497],
       [ 0.31750251, -0.76795352,  0.11579874],
       [-0.00648555, -0.22678941,  2.15460437]])

In [78]:
 # Basics:
a = np.arange(10)
a.dtype

dtype('int32')

In [83]:
# we can explicitly metion which data type we want:
b = np.arange(10,dtype = "float32")
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [86]:
# the default is float for np.zeros and np.ones:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
b = np.ones((3,3),dtype = int)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [88]:
# complex datatype:
a = np.array([1+2j, 2+6j])
a.dtype

dtype('complex128')

In [89]:
b = np.array([True, False,True,False])
b.dtype

dtype('bool')

In [91]:
c = np.array(["Vikas", "Charan","Murari"])
c.dtype

dtype('<U6')

In [ ]:
''' 
   b = boolean
   i = integer
   u = unsigned int
   f = float
   c = complex
   m = timedelta 
   M = datetime
   O = python(objects)
   S,a = (byte)-string
   u = unicode
   v = rawdata '''

In [3]:
# acess the element in array:
a = np.arange(10)
print("array: ",a)
print(a[5])

array:  [0 1 2 3 4 5 6 7 8 9]
5


In [96]:
# multi dimension array:
b = np.diag([1,2,3])
b

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [97]:
b[2,2]

3

In [98]:
# assigning value:
b[2,1] = 10
b

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 10,  3]])

In [99]:
#Slicing:

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# we can combine assignment and slicing:

b = np.arange(10) 
b[5:] = 10
b

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [19]:
# assigning
b = np.arange(5) # only 5 is possible because rage of a lies in 10
# from fifth pos b values will stick into a 
a[5:] = b[::-1]  # a[5:] = 0,1,2,3,4 b[::-1] = 4,3,2,1
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [112]:
# Copies and views:


In [113]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# copying one part of array of a to b
b = a[::2]
b

array([0, 2, 4, 3, 1])

In [23]:
# if both are same are any subset of another it gives True:
np.shares_memory(a,b)

True

In [24]:
b[0] = 10
b

array([10,  2,  4,  3,  1])

In [25]:
np.shares_memory(a,b)

True

In [26]:
# it will update a if we change b because both shares_memory:
a  

array([10,  1,  2,  3,  4,  4,  3,  2,  1,  0])

In [27]:
a = np.arange(10)

# force to copy:  returns false
c = a[::2].copy() 
c

array([0, 2, 4, 6, 8])

In [28]:
np.shares_memory(a,c)

False

In [29]:
c[0] = 1
c

array([1, 2, 4, 6, 8])

In [30]:
# here a doesnt share memory so a has no change:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Fancy Indexing:


In [32]:
a = np.random.randint(0,20,15)
a

array([ 7, 19,  8, 11,  1, 16, 14, 16, 16, 11, 14, 16, 17, 12,  3])

In [4]:
mask = (a%2 == 0) # mask mandatory

In [155]:
extract = a[mask]
extract

array([14, 14, 18, 14, 18, 14,  2])

In [161]:
# convert even numbers into any another number:
a[mask] = -1
a

array([ 5, -1,  9, -1,  5, -1,  7,  3, 15, -1, -1, 15, -1,  1, -1])

In [163]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [164]:
# indexing with repeation:
a[[2,3,4,2,4,2]]

array([20, 30, 40, 20, 40, 20])

In [165]:
# change 5,1index with another number:
a[[5,1]] = [555,111]
a

array([  0, 111,  20,  30,  40, 555,  60,  70,  80,  90])

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [4]:
a[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])