In [2]:
import numpy as np


In [8]:
# create array: and add +1 to each element to it
a = np.arange(10)
print("before adding +1: ",a)
print("after adding +1: ",a+1)

before adding +1:  [0 1 2 3 4 5 6 7 8 9]
after adding +1:  [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a+1 # known as scalar addition

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [26]:
b = np.ones(10,dtype = int)+1 # this gives twos instead of ones because +1
a - b # this does the - operation


array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
a*b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
c = np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
# matrix multiplication: both does same
print(c*c)
print("---------------")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
---------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [44]:
# check for each element and perform:
a = np.array([1,2,3,4])
b = np.array([5,2,3,4])
print(a == b)   # this gives for each element
print(np.array_equal(a,b)) # this gives according to array

[False  True  True  True]
False


In [42]:
a>b

array([False, False, False, False])

In [46]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])

np.logical_or(a,b) # or operation 

array([ True,  True,  True, False])

In [47]:
np.logical_and(a,b)

array([ True, False, False, False])

In [50]:
np.logical_xor(a,b)

array([False,  True,  True, False])

In [51]:
np.logical_not(a,b)

array([0, 0, 1, 1])

In [54]:
# print sin value of each element:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [55]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [58]:
np.log(a)  # log(0): it is not defined so it gives -inf

<ipython-input-58-25ca5454c707>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)  # log(0): it is not defined so it gives -inf


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
# print E^x of each element:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [60]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [63]:
# this gives error because values doesnt match:
a + np.array([1,3,])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [65]:
# sum of elements in array:

a = np.array([1,2,3,4])
np.sum(a)

10

In [67]:
a = np.array([[1,1], [2,2]])
a

array([[1, 1],
       [2, 2]])

In [88]:
# column-wise sum
a.sum(axis = 0) # this gives addition of 1+2 and 1+2 if axis =0

array([3, 3])

In [89]:
# row-wise sum:
a.sum(axis = 1) # this gives addition of 1+1 and 2+2 if axis =1

array([2, 4])

In [90]:
# 3-Dimension addition using axis:

b = np.array([[[1,2,3],[1,2,3]] ,[[4,5,6],[4,5,6]]])
print(b)
print(b.ndim)


[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
3


In [91]:
print(b.sum(axis = 0))
print(b.sum(axis = 1))
print(b.sum(axis = 2))

[[5 7 9]
 [5 7 9]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 6  6]
 [15 15]]


In [92]:
a = np.arange(10)
a.min()

0

In [93]:
a.max()

9

In [97]:
x = np.array([1,22,3])

# this gives index of minimum element:
x.argmin()

0

In [98]:
# this gives index of maximum element:
x.argmax()

1

In [99]:
# all : if one of them is false it gives false: logical_and

a = np.all([True,True,False,True])
a

False

In [100]:
a = np.all([True,True,True])
a

True

In [101]:
# any : if one of them is True it will be True: logical_or

b = np.any([True,False,True,False])
b

True

In [102]:
#  any can be used as array comparisions:

a = np.zeros((50,50))
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [104]:
np.any (a!=0)

False

In [105]:
np.all(a == a)

True

In [4]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
# expression gives bool .all() gives bool if all are correct
((a<=b) & (b<=c)).all()

True

In [5]:
x = np.array([1,2,3,4,5])
y = np.array([[1,2,3], [5,6,7]])

x.mean()

3.0

In [6]:
# median:

np.median(x)

3.0

In [9]:
# median with axis:

np.median(y,axis = 1)

array([2., 6.])

In [10]:
# standard deviation:

x.std()

1.4142135623730951

In [18]:
data = np.loadtxt("populations.txt")
data


array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [19]:
year,hare,lynx,carrot = data.T
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [20]:
hare

array([30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
       22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
       11200.,  7600., 14600., 16200., 24700.])

In [24]:
# [:,1:] :,->choose everything and [1:] select only these:
populations = data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [25]:
populations.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [30]:
# which species has the least population in each year:
np.argmin(populations,axis = 1)

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1],
      dtype=int64)

In [31]:
# which species has the highest population in each year:
np.argmax(populations,axis = 1 )

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [32]:
# Broadcasting:
'''  
normal_matrix_addition:
    
matrix1:                  matrix2:    
 
[ 0   0    0             [ 0  1  2      [ 0   1  2   
  10  10  10               0  1  2    =  10  11  12 
  20  20  20      +        0  1  2       20  21  22 
  30  30  30 ]             0  1  2 ]     30  31  32 ] 

Broadcasting:
    
# which values # are there for matrix 2 will be not present:
# it will replicate them
 
 matrix1:                matrix2:              
[ 0   0    0             [ 0  1  2      [ 0   1  2   
  10  10  10           #   0  1  2    =  10  11  12 
  20  20  20      +    #   0  1  2       20  21  22 
  30  30  30 ]         #   0  1  2 ]     30  31  32 ]   '''    
    

In [43]:
# (0,40,10) are done by slicing:
#(3,1) 3: make the values 3 times 1: per each row
a = np.tile(np.arange(0,40,10), (3,1))
print(a)

# see the difference between (3,1)&(3,2):
print("--------------------------")
b = np.tile(np.arange(0,40,10), (3,2))
print(b)

# make it as transpose matrix:
print("---------------------------")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
--------------------------
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
---------------------------
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [44]:
# here i have given only one array: 
#but it creates own by extra 3 rows and add it 

b = np.array([0,1,2]) 
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [54]:
# here comes the broad casting concept:
a = np.arange(0,40,10)
print(a.shape)
print(a)  # here it is 1-d array (4,)-> 4-rows,0-columns

(4,)
[ 0 10 20 30]


In [55]:
a = a[:,np.newaxis]   # here it becomes 2-D array
print(a.shape)
print(a)  # (4,1)-> 4:rows,1:column

(4, 1)
[[ 0]
 [10]
 [20]
 [30]]


In [56]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [57]:
# Flattening:

In [58]:
# ravel() it returns continue of 2-d array or anything to 1-D array
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [60]:
# transpose Matrix:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [62]:
# Reshaping:


In [65]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [67]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [69]:
# reshape gives the actual form of matrix: 
# for (2,3) matrix we need 6 elements if we give 5 it gives error

b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# if we change an element in b it reflects a :
# both referers to same location in memory:
b[0,0] = 12
print("a: ", a)

print("b: ", b)

a:  [[12  2  3]
 [ 4  5  6]]
b:  [[12  2  3]
 [ 4  5  6]]


In [74]:
# Adding a Dimension:


In [75]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [76]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [77]:
# Dimension Shuffling:


In [79]:
# 4 X 3 X 2: matrix 4: matrices 3X2:matrix type 
# this is 3-D array

a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [80]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [82]:
# Accesing element:
# 0: matrix 2:row 1:column
a[0,2,1]

5

In [84]:
# Resiging:
 
b = np.arange(4)
# here it will resize exactly 4 elements and next it goes with 0
b.resize((8,))
b

array([0, 1, 2, 3, 0, 0, 0, 0])

In [85]:
# now c,b refers to same location if u resize again b it gives error
c = b
b.resize((4,))  

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [86]:
# sorting Data:


In [90]:
# sorting along axis:

a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis = 1) #axis = 1 does sort with respective row 
b

array([[4, 5, 6],
       [2, 2, 3]])

In [91]:
a.sort(axis = 1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [94]:
# Fancy indexing:

#argsort: it sorts according to the index values
# so here b are index values and a is like array
# call by array[index]:a[b]

a = np.array([4,3,1,2])
b = np.argsort(a)
b

array([2, 3, 1, 0], dtype=int64)

In [95]:
a[b]

array([1, 2, 3, 4])